-- AlterTable
ALTER TABLE "Page" ADD COLUMN "restaurantModeEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Page" ADD COLUMN "restaurantLat" DOUBLE PRECISION;
ALTER TABLE "Page" ADD COLUMN "restaurantLng" DOUBLE PRECISION;
ALTER TABLE "Page" ADD COLUMN "deliverySlabsJson" TEXT;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN "deliveryLat" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN "deliveryLng" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN "deliveryFee" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN "deliveryDistanceKm" DOUBLE PRECISION;
